[package]
name = "throwaway-miette-gh-action-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
miette = { version = "7.2.0", features = ["fancy"] }
semver = "1.0.22"
thiserror = "1.0.59"
