name: main

on:
  workflow_dispatch: # allows manual triggering

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Build and Run Crate
        env:
          CLICOLOR_FORCE: 1
        run: |
          script --return --quiet --log-out /dev/null --command "unset NO_COLOR && nix eval --expr 'blah'"
          nix develop --command cargo run
