name: main

on:
  workflow_dispatch: # allows manual triggering

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Build and Run Crate
        env:
          CLICOLOR_FORCE: 1
          NO_COLOR: "" # Just to make sure it's unset
          TERM: xterm # work around for nix
        shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
        run: |
          nix eval --expr 'blah'
          # nix develop --command cargo run
